version: '3.7'
services:

  mysql_db:
    image: mysql:8
    ports:
      - '3306:3306'
    environment:
      - MYSQL_USER=app
      - MYSQL_PASSWORD=pass
      - MYSQL_DATABASE=app
      - MYSQL_RANDOM_ROOT_PASSWORD=yes

  postgres_db:
    image: postgres:12
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=app

  node_app:
    build: ./gate-simulator
    ports:
      - '9999:9999'